cd src
python run.py\
    --mode=search \
    --task_seed=0 \
    --seed=0 \
    --experiment="miniimagenet" \
    --approach=pn \
    --model=resnet \
    --id=001 \
    --lr=0.025 \
    --lamb=0.03 \
    --epochs=50 \
    --batch=64 \
